一、DataFrame类似于一个二维矩阵，但是行列都有对应的索引。

In [1]:
import pandas as pd
import numpy as np

#法1：通过字典创建
dict_={'A':[1,2,3],
       'B':[2,3,4],
       'C':[3,4,5]}
data=pd.DataFrame(dict_)
data

A  B  C
0  1  2  3
1  2  3  4
2  3  4  5

In [2]:
#法2：通过元组创建
name=['a','b','c']
age=[1,2,3]
list_=list(zip(name,age))
data1=pd.DataFrame(list_,columns=['name','age'])
data1

name  age
0    a    1
1    b    2
2    c    3

In [3]:
#法3：randn随机生成
columns=['1','2','3']
index=list(range(0,3))
data2=pd.DataFrame(np.random.randn(3,3),
                        columns=columns)
print(type(data2))
data2

<class 'pandas.core.frame.DataFrame'>


1         2         3
0 -0.556719  0.435856  1.073438
1  1.361178  0.761014 -2.103011
2  1.530245 -1.047451  1.436790

二、Series可以当成DataFrame中一个元素，一列索引对应一列值

In [4]:
#法1：通过字典创建
dict3={'a':1,'b':2,'c':3}
data3=pd.Series(dict3)
print(type(data3))
data3

<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64

In [5]:
#法2：通过列表创建
data4=pd.Series([1,2,3],index=['a','b','c'])
print(type(data4))
data4

<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64

In [6]:
#法3：通过arange创建
data5=pd.Series(np.arange(3),index=['a','b','c'])
print(type(data5))
data5

<class 'pandas.core.series.Series'>


a    0
b    1
c    2
dtype: int32

三、array数组

In [7]:
data6=np.array([[1,2,3],[4,5,6]])
print(type(data6))
data6

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

四、tensor<br>
下面代码中，Tensor 是类，tensor 和 as_tensor则是方法，第一种生成的是浮点型，后两种生成数据的类型和传入数据类型一致，也就是说传入整型生成整型，传入浮点型生成浮点型。

In [8]:
import torch

data7=torch.Tensor([1,2,3])
print(data7,data7.dtype)

data8=torch.tensor([1,2,3])
print(data8,data8.dtype)

data9=torch.as_tensor([1.,2.,3])
print(data9,data9.dtype)

tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32


转化

In [12]:
#1.DataFrame拆解Series：索引出的单行或者单列的数据类型为Series
print(type(data['A']))
data['A']

<class 'pandas.core.series.Series'>


0    1
1    2
2    3
Name: A, dtype: int64

In [13]:
data.iloc[0,:]

A    1
B    2
C    3
Name: 0, dtype: int64

In [14]:
#2.DataFrame转array
data.values

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int64)

In [15]:
data_arr=np.array(data)
data_arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int64)

In [16]:
#3.Series转DataFrame
series1=data['A']
series2=data['B']
data_se=pd.DataFrame({'A':series1,'B':series2})
data_se

A  B
0  1  2
1  2  3
2  3  4

In [17]:
series1.to_frame()

A
0  1
1  2
2  3

In [18]:
#4.Series转array
series1.values

array([1, 2, 3], dtype=int64)

In [21]:
np.array((series1,series2))

array([[1, 2, 3],
       [2, 3, 4]], dtype=int64)

In [22]:
#5.array转DataFrame
data10=pd.DataFrame(data6,columns=['a','b','c'])
data10

a  b  c
0  1  2  3
1  4  5  6

In [23]:
#6.array转Series
arr1=np.array([1,2,3])
data11=pd.Series(arr1,index=['a','b','c'])
print(type(data11))
data11

<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int32

In [24]:
#7.array转tensor
arr2=np.array([4,5,6])
ten=torch.from_numpy(arr2)
ten

tensor([4, 5, 6], dtype=torch.int32)

In [25]:
#8.tensor转array
arr3=ten.numpy()
arr4=ten.cpu().numpy()
arr3

array([4, 5, 6])